"""Initial migration - baseline

Revision ID: 15a96db54551
Revises: 
Create Date: 2025-12-29 11:44:21.335851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a96db54551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doctors_slug_key', 'doctors', type_='unique')
    op.drop_index('ix_doctors_slug', table_name='doctors')
    op.create_index(op.f('ix_doctors_slug'), 'doctors', ['slug'], unique=True)
    op.drop_constraint('services_slug_key', 'services', type_='unique')
    op.drop_index('ix_services_slug', table_name='services')
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.create_index('ix_services_slug', 'services', ['slug'], unique=False)
    op.create_unique_constraint('services_slug_key', 'services', ['slug'])
    op.drop_index(op.f('ix_doctors_slug'), table_name='doctors')
    op.create_index('ix_doctors_slug', 'doctors', ['slug'], unique=False)
    op.create_unique_constraint('doctors_slug_key', 'doctors', ['slug'])
    # ### end Alembic commands ###
